language: python
os: linux
dist: focal

python:
  - "3.7"
  # - "3.8"

cache:
  directories:
    - $HOME/.cache/pip

services:
  - xvfb
install:
  - pip install .

before_script:
  - export DISPLAY=:99.0

script:
  - pytest
