#! /usr/bin/env python

# fix the type annotatiton of not yet undefined classes
from __future__ import annotations
import os
import sys

# Set environment variables BEFORE any other imports
# Suppress outdated package warnings
os.environ.setdefault("OUTDATED_IGNORE", "1")

# Suppress Python warnings at environment level (applies before any imports)
if "PYTHONWARNINGS" not in os.environ:
    os.environ["PYTHONWARNINGS"] = "ignore"

import logging
from functools import partialmethod
from pathlib import Path as _Path

# Suppress pkg_resources deprecation warnings - must be set BEFORE any imports
import warnings

# Configure warning filters to suppress common noisy warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", module="outdated")
warnings.filterwarnings("ignore", module="pkg_resources")

# Fix macOS threading issues with scipy/numpy imports
# Must be set BEFORE importing any packages that use scipy/numpy
if sys.platform == "darwin":  # macOS
    # Limit threading to avoid mutex/deadlock issues on macOS
    os.environ.setdefault("OMP_NUM_THREADS", "1")
    os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
    os.environ.setdefault("MKL_NUM_THREADS", "1")
    os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
    os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")

from outdated import warn_if_outdated
from joblib import Memory
import matplotlib
import matplotlib.pyplot as plt
import seaborn as _sns

try:
    # Even though there is no "imc/_version" file,
    # it should be generated by
    # setuptools_scm when building the package
    from imc._version import version

    __version__ = version
except ImportError:
    from setuptools_scm import get_version as _get_version

    version = __version__ = _get_version(root="..", relative_to=__file__)


# Suppress warnings during version check
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    try:
        warn_if_outdated("imc", __version__)
    except Exception:
        pass  # Silently ignore any errors in version checking

plt.rcParams["svg.fonttype"] = "none"
plt.rcParams["font.family"] = "Arial"
plt.rcParams["font.sans-serif"] = ["Arial"]
plt.rcParams["text.usetex"] = False

import scanpy as _sc

_sc.settings.n_jobs = -1


def setup_logger(name: str = "imc", level: int = logging.INFO) -> logging.Logger:
    """Setup the logger for the package."""
    logger = logging.getLogger(name)
    logger.setLevel(level)

    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(level)
    formatter = logging.Formatter("%(asctime)s - %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    return logger


LOGGER = setup_logger()

# Setup joblib memory
_Path.mkdir = partialmethod(_Path.mkdir, exist_ok=True, parents=True)
JOBLIB_CACHE_DIR = _Path("~/.imc").expanduser()
JOBLIB_CACHE_DIR.mkdir()
MEMORY = Memory(location=JOBLIB_CACHE_DIR, verbose=0)

# Decorate seaborn clustermap
# _sns.clustermap = colorbar_decorator(_sns.clustermap)


from imc.data_models.project import Project
from imc.data_models.sample import IMCSample
from imc.data_models.roi import ROI
