# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test imc package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel pytest
        pip install .[deepcell]
    - name: Test with pytest
      run: |
        # Test package
        python -m pytest imc/

        # Run example processing pipeline
        SAMPLE=20200629_NL1915A
        MCD_URL=https://zenodo.org/record/4110560/files/data/${SAMPLE}/${SAMPLE}.mcd

        # Get example data (will be cached by github action)
        mkdir -p /home/$USER/.imc/ imctest/data
        if [ ! -f /home/$USER/.imc/${SAMPLE}.mcd ]; then
          echo "Downloading test dataset..."
          wget -q -O /home/$USER/.imc/${SAMPLE}.mcd $MCD_URL
          echo "Finished downloading."
        fi
        ln -s /home/$USER/.imc/${SAMPLE}.mcd imctest/data/${SAMPLE}.mcd

        # Run pipeline
        cd imctest/
        imc process data/${SAMPLE}.mcd

        # List output files
        ls -l processed/
        ls -l processed/${SAMPLE}
    - name: Cache resources
      id: cache-resources
      uses: actions/cache@v2
      with:
        path: /home/$USER/.imc
        key: imc-resources-linux

  osx:
    runs-on: macos-10.14
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel pytest
        pip install .[deepcell]
    - name: Test with pytest
      run: |
        # Test package
        python -m pytest imc/

        # Run example processing pipeline
        SAMPLE=20200629_NL1915A
        MCD_URL=https://zenodo.org/record/4110560/files/data/${SAMPLE}/${SAMPLE}.mcd

        # Get example data (will be cached by github action)
        mkdir -p /Applications/imc/ imctest/data
        if [ ! -f /Applications/imc/${SAMPLE}.mcd ]; then
          echo "Downloading test dataset..."
          wget -q -O /Applications/imc/${SAMPLE}.mcd $MCD_URL
          echo "Finished downloading."
        fi
        ln -s /Applications/imc/${SAMPLE}.mcd imctest/data/${SAMPLE}.mcd

        # Run pipeline
        cd imctest/
        imc process data/${SAMPLE}.mcd

        # List output files
        ls -l processed/
        ls -l processed/${SAMPLE}
        ls -l processed/phenotyping
    - name: Cache resources
      id: cache-resources
      uses: actions/cache@v2
      with:
        path: /home/$USER/.imc
        key: imc-resources-osx
