# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test imc package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .[deepcell]
    - name: Cache resources
      id: cache-resources
      uses: actions/cache@v2
      with:
        path: /home/runner/.imc
        key: imc-resources
    - name: Test with pytest
      run: |
        # Test package
        python -m pytest imc/
        
        # Run example processing pipeline
        SAMPLE=20200629_NL1915A
        MCD_URL=https://zenodo.org/record/4110560/files/data/${SAMPLE}/${SAMPLE}.mcd

        # Get example data (will be cached by github action)
        mkdir -p imctest/data
        if [! -f /home/runner/.imc/data/${SAMPLE}.mcd ]; then
          echo "Downloading..."
          wget -q -O imctest/data/${SAMPLE}.mcd $MCD_URL
          echo "Finished."
        fi
        ln -s /home/runner/.imc/data/${SAMPLE}.mcd imctest/data/${SAMPLE}.mcd

        # Run pipeline
        cd imctest/

        ## output description of acquired data
        imc inspect data/${SAMPLE}.mcd

        ## convert MCD to TIFF and auxiliary files
        imc prepare \
          --ilastik --n-crops 0 --ilastik-compartment nuclear \
          data/${SAMPLE}.mcd

        ## For each TIFF file, output prediction of mask probabilities and segment them 
        TIFFS=processed/${SAMPLE}/tiffs/${SAMPLE}*_full.tiff
        imc predict $TIFFS
        imc segment \
          --from-probabilities --model deepcell --compartment both $TIFFS

        ## Quantify channel intensity for each single cell in every image
        imc quantify $TIFFS

        ls -l processed/
        ls -l processed/${SAMPLE}
