# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test imc package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel pytest
        pip install .[deepcell,astir]
    - name: Test with pytest
      run: |
        # Test package
        python -m pytest imc/

        # Run pipeline
        mkdir -p imctest
        cd imctest
        imc process https://zenodo.org/record/5018260/files/COVID19_brain_Patient03_ROI3_COVID19_olfactorybulb.txt?download=1

        # List output files
        ls -l processed/
        ls -l processed/${SAMPLE}
        ls -l results/phenotyping
    - name: Cache resources
      id: cache-resources
      uses: actions/cache@v4
      with:
        path: /home/$USER/.imc
        key: imc-resources-linux

  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel

        # Core scientific stack (pin to stable, binary-available builds)
        pip install "numpy<2.0" "scipy>=1.11,<1.16" "pandas>=2.0,<3.0" "matplotlib>=3.7,<3.11" \
                    "scikit-image==0.19.3" "tifffile==2021.11.2" "networkx>=2.6,<3.0" \
                    "seaborn>=0.13,<0.14" "fastcluster==1.2.6"

        # Core dependencies for IMC and ecosystem
        pip install "imctools>=2.1.8" "joblib>=1.2,<1.6" "leidenalg>=0.10.2" \
                    "python-louvain>=0.16" "scanpy>=1.9,<1.12" "bbknn>=1.6" \
                    "numpy-groupies>=0.9,<0.12" "parmap>=1.6,<2.0" \
                    "seaborn-extensions>=0.2.1" "outdated>=0.2.2" "ordered-set>=4.1.0" "urlpath>=1.2.0" "PyYAML>=6.0"

        # Optional backends used in your environment
        pip install "astir==0.1.5" "DeepCell==0.12.6"

        # Finally install your package
        pip install -e .
    - name: Test with pytest
      run: |
        # Test package
        python -m pytest imc/

        # Run example processing pipeline
        mkdir -p imctest
        cd imctest
        imc process https://zenodo.org/record/5018260/files/COVID19_brain_Patient03_ROI3_COVID19_olfactorybulb.txt?download=1

        # List output files
        ls -l processed/
        ls -l processed/${SAMPLE}
        ls -l results/phenotyping
    - name: Cache resources
      id: cache-resources
      uses: actions/cache@v4
      with:
        path: /home/$USER/.imc
        key: imc-resources-osx
